name: mbml
channels:
  - conda-forge
dependencies:
  - tensorflow
  - python=3.9
  - pip=22.0.2
  - ipykernel
  - wget
  - pip:
    - numpyro==0.9.1
    - numpy==1.22.3
    - matplotlib==3.5.1
    - pystan==2.19.1.1
    - seaborn==0.11.2
    - scikit-learn==1.0.2
    - tqdm==4.62.3
    - pyro-ppl==1.8.0
